- HISTORY.rst
- config/settings/base.py
- config/urls.py
- docker/Dockerfile
- docs_manual/admin_config.rst
- varfish/templates/users/login.html
Basic adjustments to enable SAML authentication in VarFish. Most parts of the code are copied from the respective sodar-core files.
Note that for a working SAML authentication, it is very likely that users have to change the `ATTRIBUTES_MAP` fields in the saml config for the specific names. Therefore these fields should most likely be configurable through `env` as well.
> SAML Configuration

- HISTORY.rst
- variants/views.py
> Fix issue with variant annotation export (#328)

- docs_manual/developer_installation.rst
Postgres version (12) still missing.
> Updates to developer_installation.rst

- HISTORY.rst
- docs_manual/admin_upgrade.rst
Related-Issue: #450
Closes: #450
Projected-Results-Impact: require-revalidation
> Documenting problems and fix with 20210728 data release (#450)

- HISTORY.rst
- varfish/static/js/filter_form.js
- variants/query_presets.py
- variants/templates/variants/filter_result/header.html
- variants/templates/variants/filter_result/row.html
- variants/templates/variants/var_details/clinvar.html
- variants/tests/test_query_presets.py
Properly display the clinvar annotations that we have in the database (#464).
Adjusting default frequency filters for "clinvar pathogenic" filter: remove all threshold (#464).
Adding note about difference with upstream Clinvar (#464).
Related-Issue: #464
Closes: #464
Projected-Results-Impact: require-revalidation
> Adjustments/fixes in the "Clinvar pathogenic" filter (#464)

- variants/templates/variants/filter_result/row.html
Closes: #516
Related-Issue: #516
> Fixing IGV and MT dropdown menu bug.

- HISTORY.rst
- config/settings/base.py
- variants/file_export.py
- variants/models.py
- variants/templates/variants/variant_details.html
- variants/tests/test_file_export.py
Closes: https://github.com/bihealth/varfish-server/issues/495
Related-Issue: https://github.com/bihealth/varfish-server/issues/495
Project-Results-Impact: none
These are the changes required to export extra_annotation table to xls and tsv.
Tests are included
P.S. Not so sure how test with and without Extra Anno active. So please note
VARFISH_ENABLE_EXTRA_ANNOS = env.bool("VARFISH_ENABLE_EXTRA_ANNOS", True)
That would change the default setting.
Otherwise the code is pretty straighforward there is 
RowWithExtraAnno that wrap the result table in order to make the exporters working with the additional columns.
The additional columns are added in the base exported when extra anno option is active, the expansion is based on the fields in the database
> Extra annotations in export completed and tested

- HISTORY.rst
- geneinfo/tests/factories.py
- variants/file_export.py
- variants/models.py
- variants/queries.py
- variants/tests/factories.py
- variants/tests/test_file_export.py
- variants/views.py
Closes: #568
Related-Issue: #568
> Add Transcripts GnomadAD constraints and clinvar reports in the export

- HISTORY.rst
- docs_manual/admin_upgrade.rst
- svs/bg_db.py
- variants/migrations/0033_smallvariantsummary.py
- variants/migrations/0044_adjust_smallvariantstats.py
- variants/migrations/0046_partition_smallvariants_table.py
- variants/migrations/0086_smallvariantsummary_excludefrominhousedb.py
- variants/plugins.py
> 579 allow to mark cases for exclusion in background database

- HISTORY.rst
- variants/file_export.py
- variants/queries.py
- variants/tests/test_queries.py
- variants/tests/test_views.py
Related-Issue: #565
Closes: #565
Projected-Results-Impact: require-revalidation
> Create single result row even if multiple clinvar entries (#565)

- cases/vueapp/src/common.ts
- cases/vueapp/src/components/CaseDetail/PaneAnnotations.vue
- variants/vueapp/src/api/variantClient.ts
- variants/vueapp/src/components/FilterApp.vue
- variants/vueapp/src/components/FilterResultsTable.vue
- variants/vueapp/src/stores/variantResultSet.ts
> fix: adding back default columns

- varfish/vueapp/src/varfish/api/annonars.ts
- varfish/vueapp/src/varfish/components/VegaPlot.vue
- variants/vueapp/src/components/VariantDetails.vue
- variants/vueapp/src/components/VariantDetails/Clinvar.vue
- variants/vueapp/src/components/VariantDetails/ClinvarFreqPlot.vue
- variants/vueapp/src/components/VariantDetails/Gene.vue
- variants/vueapp/src/components/VariantDetails/GtexGenePlot.vue
- variants/vueapp/src/stores/variantDetails.ts
> feat: display ClinVar and GTEx values for each gene (#672, #68)

- svs/models/jobs.py
- variants/models/jobs.py
> fix: case not set on result set creation

- cases_import/models/executors.py
- cases_qc/io/cramino.py
- cases_qc/io/dragen.py
- cases_qc/io/ngsbits.py
- cases_qc/io/samtools.py
- cases_qc/tests/test_views_api.py
> fix: resolve pylance issue with subscription of dict

- cases/vueapp/src/components/CaseDetail/CardAnnotations.vue
- cases/vueapp/src/components/CaseDetail/Content.vue
> fix: display of variant annotation counts are static always (#1376)

- svs/vueapp/src/components/SvFilterApp.vue
- svs/vueapp/src/components/SvFilterResultsTable.vue
- svs/vueapp/src/stores/svQuery.js
- variants/vueapp/src/components/FilterApp.vue
- variants/vueapp/src/components/FilterResultsTable.vue
- variants/vueapp/src/stores/variantQuery.js
> feat: keep scroll position after viewing variant details (#1273)

- Pipfile
- Pipfile.lock
- utils/kickoff_orphaned_annotation_query.py
- utils/projectwide_query.py
- variants/file_export.py
- variants/serializers/__init__.py
- variants/utils.py
- variants/views/api/__init__.py
> fix: xlsx file export issues (#1504)

- cases/vueapp/src/components/CaseDetail/CardQueries.vue
- cases/vueapp/src/components/CaseDetailApp.vue
- cases/vueapp/src/stores/caseDetails.ts
- svs/vueapp/src/components/SvFilterApp.vue
- svs/vueapp/src/components/SvFilterForm/QuickPresets.vue
- svs/vueapp/src/stores/svQuery.js
- variants/vueapp/src/components/FilterApp.vue
- variants/vueapp/src/stores/variantAcmgRating/store.ts
- variants/vueapp/src/stores/variantComments.ts
- variants/vueapp/src/stores/variantFlags.ts
- variants/vueapp/src/stores/variantQuery.js
- variants/vueapp/src/stores/variantResultSet.ts
> fix: changed query presets not updated in filter form (#1557)

- frontend/src/cases/components/CaseDetail/CardTerms.vue
- frontend/src/variants/components/HpoTermInput.vue
> feat: make omim search case insensitive (#1788)

- frontend/end-to-end-tests/seqvar-filtration.spec.ts
- frontend/src/seqvars/components/QualityControls.vue
- frontend/src/seqvars/components/genotype/GenotypeControls.vue
- frontend/src/seqvars/components/genotype/InheritanceModeControls.vue
- frontend/src/seqvars/components/ui/CollapsibleGroup.vue
- frontend/src/seqvars/views/SeqvarsFiltration.vue
Samples a few form elements to check whether the preset-expected values are set. It does not cover 100% yet.
As so often with end to end test, a positive side effect are more accessibility attributes, semantic elements.
> test: seqvars e2e for preset values
