varfish-org/varfish-server

- svs/models.py
- svs/tests/test_models.py
- svs/tests/test_queries.py
> Fixing problem with SV clean up job.

- HISTORY.rst
- docker/Dockerfile
> 96 fix disabled site wide apps

- HISTORY.rst
- config/settings/base.py
- requirements/base.txt
- requirements/local.txt
- requirements/test.txt
- variants/models.py
- variants/plugins.py
> Bumping dependencies

- HISTORY.rst
- docs_manual/admin_config.rst
- docs_manual/admin_tuning.rst
> Extending documentation

- HISTORY.rst
- variants/templates/variants/case_detail.html
- variants/templates/variants/case_list.html
- variants/templates/variants/case_update.html
- variants/templates/variants/case_update_terms.html
- variants/templates/variants/filter.html
> Allow copying case UUIDs from page headers

- HISTORY.rst
- beaconsite/tests/test_permissions_ajax.py
- clinvar_export/tests/test_permissions_ajax.py
- clinvar_export/tests/test_views_ajax.py
- clinvar_export/views_ajax.py
- geneinfo/models.py
- variants/models.py
- variants/templates/variants/case/detail_annotation.html
- variants/templates/variants/case_list/annotation.html
- variants/tests/test_views.py
- variants/urls.py
- variants/views.py
> Improvements to user annotation display/download.

- docker/Dockerfile
- docs_manual/admin_upgrade.rst
- variants/templates/variants/kiosk_home.html
> Improving deployability with Docker Compose (Kiosk & Demo)

- HISTORY.rst
- config/settings/base.py
- variants/plugins.py
> Fix search & Sentry integration

- HISTORY.rst
- docker/Dockerfile
> Fixing problems with docker image build

- docker/docker-entrypoint.sh
> Remove makemigrations from docker-entrypoint.sh

- HISTORY.rst
- config/settings/base.py
> Added settings parameter disable_categories

- HISTORY.rst
- config/celery.py
- config/settings/base.py
- docs_manual/tutorials_kiosk.rst
- varfish/users/models.py
- varfish/utils.py
- variants/models.py
- variants/templates/variants/kiosk_home.html
- variants/views.py
> Fix varfish-kiosk crash (#215)

- HISTORY.rst
- docs_manual/bug_reports.rst
- docs_manual/index.rst
- variants/templates/variants/_search_item.html
- variants/tests/test_ui.py
Extended manual for bug report workflow (#238)
> Fixing broken search field.

- docker/Dockerfile
- importer/plugins.py
> Fixing Dockerfile to pull iconify icons.

- HISTORY.rst
- requirements/base.txt
This works around a performance issue in `sodar-core` (internal ticket created for `sodar-core`, will be fixed in later versions).
closes #303
> Improving performance of project overview (#304)

- HISTORY.rst
- varfish/vueapp/src/components/SubmissionList.vue
- varfish/vueapp/src/helpers.js
- varfish/vueapp/src/store/modules/clinvarExport.js
> Fixing issue with multiple added variants (#283)

- HISTORY.rst
- clinvar_export/tests/test_permissions_ajax.py
- clinvar_export/tests/test_views_ajax.py
- clinvar_export/urls.py
- clinvar_export/views_ajax.py
- varfish/static/js/variant_validator.js
- varfish/vueapp/src/api/clinvarExport.js
- varfish/vueapp/src/components/SubmissionList.vue
- varfish/vueapp/src/store/modules/clinvarExport.js
> Make clinvar work with many user annotations (#302)

- HISTORY.rst
- variants/models.py
> Fixing CADD annotation (#313)

- HISTORY.rst
- variants/templates/variants/case_update_terms.html
> Adding mitochondrial inh. to case phenotype (#325)

- variants/views.py
> Another fix to variant annotation export (#328)

- .github/workflows/ci.yml
- HISTORY.rst
> Adding more postgres versions to CI (#337)

- .github/workflows/ci.yml
- HISTORY.rst
- variants/migrations/0041_array_cat_agg.py
> Make migrations compatible with Postgres 14 (#338).

- HISTORY.rst
- svs/templates/svs/filter_result/table.html
- varfish/static/js/flags_comments.js
- varfish/static/js/variant_comments.js
- variants/models.py
- variants/templates/variants/_single_acmg_criteria_form_tpl.html
- variants/templates/variants/case/detail_annotation.html
- variants/templates/variants/case_detail.html
- variants/templates/variants/filter_result/table.html
- variants/templatetags/variants_tags.py
- variants/tests/test_views.py
- variants/views.py
> Allowing update of annotations on case details page (#344, #348)

- HISTORY.rst
- variants/queries.py
> Improving performance for fetching result queries (#371)

- HISTORY.rst
- variants/queries.py
- variants/templates/variants/filter_result/header.html
- variants/templates/variants/filter_result/row.html
- variants/templates/variants/filter_result/table.html
- variants/tests/test_queries.py
- variants/tests/test_ui.py
- variants/views.py
This is a clean branch that addresses the previous comments. 
Closes [#242](https://github.com/bihealth/varfish-server/issues/242).
> Add extra annotations scores to the filtered variants (#242).

- HISTORY.rst
- variants/queries.py
Closes: #379
Related-Issue: #379
> Fixing bug in project/cohort filter (#379)

- HISTORY.rst
- importer/models.py
Closes: #386
Related-Issue: #386
> Fixing problem with CNV import (#386)

- HISTORY.rst
- variants/models.py
Related-Issue: #389
Closes: #389
> Adding index to improve beaconsite performance (#389)

- HISTORY.rst
- beaconsite/views_ajax.py
Related-Issue: #388
Closes: #388
> Strip trailing slashes in beconsite entrypoints (#388)

- HISTORY.rst
- variants/templates/variants/case/detail_annotation.html
- variants/templatetags/variants_tags.py
> Fixing crash of case detail view (#404)

- HISTORY.rst
- docs_manual/admin_upgrade.rst
> Preparing RC v1.1.1 (#406)

- HISTORY.rst
- variants/views.py
> Fixing bug in corner case of multi variant annotation (#412)

- HISTORY.rst
- clinvar_export/templates/submission_set/entrypoint.html
- config/settings/base.py
- requirements/base.txt
- svs/templates/svs/filter.html
- svs/templates/svs/import_job_detail.html
- variants/templates/variants/_case_detail_buttons.html
- variants/templates/variants/case_detail.html
- variants/templates/variants/case_list.html
- variants/templates/variants/case_update_terms.html
- variants/templates/variants/distiller_job_detail.html
- variants/templates/variants/export_job_detail.html
- variants/templates/variants/export_project_cases_job_detail.html
- variants/templates/variants/filter.html
- variants/templates/variants/filter_job_detail.html
- variants/templates/variants/import_job_detail.html
- variants/templates/variants/kiosk_home.html
- variants/templates/variants/kiosk_status.html
- variants/templates/variants/project_stats_job_create.html
- variants/templates/variants/project_stats_job_detail.html
- variants/templates/variants/spanr_job_detail.html
- variants/templates/variants/sync_job_detail.html
- variants/templates/variants/variant_details.html
> Fixing various UI glitches (#409)

- HISTORY.rst
- variants/file_export.py
Related-Issue: #417
Closes: #417
> Fixing bug in XLSX export (#417)

- varfish/static/js/variant_validator.js
Related-Issue: #284
Closes: #284
> Fixing issue with fa-solid:refresh icon (#284)

- HISTORY.rst
- docs_manual/admin_ingest.rst
- docs_manual/api_json_schemas.rst
- docs_manual/developer_templates.rst
- importer/qc_schemas.py
- importer/schemas/case-qc-v1.json
- importer/schemas/examples/trio.json
- importer/tests/test_schemas.py
- variants/schemas/case-query-v1.json
Related-Issue: #428
Closes: #428
> Schema and documentation for case QC info (#428)

- HISTORY.rst
- docs_manual/api_beacon.rst
- svs/templates/svs/filter_form/genelists.html
- varfish/static/js/panelapp.js
- variants/forms.py
- variants/queries.py
- variants/templates/variants/filter_form/genelists.html
Related-Issue: #432
Closes: #432
> Switching to using HGNC gene IDs for PanelApp (#432)

- HISTORY.rst
- docs_manual/admin_backup.rst
- docs_manual/index.rst
- importer/management/commands/pg_dump.py
Related-Issue: #430
Closes: #430
> Adding pg_dump admin command and documentation (#430)

- HISTORY.rst
- docker/Dockerfile
No-Related-Issue: small docker build change only
> Install postgres client in same version as server for docker compose

- HISTORY.rst
- docs_manual/admin_upgrade.rst
Related-Issue: #443
Closes: #443
> Preparing v1.2.0 release (#443)

- HISTORY.rst
- docs_manual/admin_upgrade.rst
Related-Issue: #450
Closes: #450
Projected-Results-Impact: require-revalidation
> Documenting problems and fix with 20210728 data release (#450)

- HISTORY.rst
- variants/templates/variants/_filter_form.html
Related-Issue: #478
Closes: #478
> Disable link-out to CADD/SPANR for multi-case form

- HISTORY.rst
- docs_manual/admin_install.rst
- docs_manual/admin_upgrade.rst
- docs_manual/developer_data_builds.rst
- docs_manual/release_cycle.rst
Related-Issue: #479
Closes: #479
> Adjusting wrong release name to "anthenea" (#479).

- HISTORY.rst
- varfish/static/js/variant_carrier.js
- variants/templates/variants/filter_result/row.html
- variants/templates/variants/filter_result/variant_carriers_result.html
- variants/templates/variants/scripts.html
- variants/templatetags/variants_tags.py
- variants/tests/test_views.py
- variants/urls.py
- variants/views.py
backport to anthenea for #492 
Related-Issue: #470
Closes: #470
> Adding "variant carrier" popup modal (#470).

- variants/templates/variants/filter_result/row.html
> Backport for fixing IGV and MT dropdown menu bug.

- HISTORY.rst
- docs_manual/admin_extras.rst
- variants/templates/variants/filter_result/row.html
> Fixing CADD setup documentation. (#520)

- HISTORY.rst
- variants/templates/variants/_multi_variant_flag_form_tpl.html
- variants/templates/variants/_variant_flag_form_tpl.html
Closes: #297
Related-Issue: #297
> Made flag filter and flag form nomenclature consistent

- HISTORY.rst
- utility/install_chrome.sh
- utility/install_chrome_gitlab.sh
- utility/install_ldap_dependencies.sh
- utility/install_os_dependencies.sh
- utility/install_os_gitlab.sh
- utility/install_python_dependencies.sh
- utility/install_vue_dev.sh
Closes: #531
Related-Issue: #531
Project-Results-Impact: none
> Updating utility/*.sh scripts from sodar-server

- HISTORY.rst
- docs_manual/developer_installation.rst
- utility/install_vue_dev.sh
Closes: #533
Related-Issue: #533
> Improved developer setup documentation.

- HISTORY.rst
- variants/templates/variants/filter_result/row.html
Closes: #523
Related-Issue: #523
> Fixed broken VariantValidator query.

- HISTORY.rst
- svs/templates/svs/_filter_form.html
- variants/templates/variants/_filter_form.html
Closes: #508
Related-Issue: #508
> Converted broken tooltip to standard title on Filter & Display button

- HISTORY.rst
- varfish/users/tasks.py
Closes: #570
Related-Issue: #570
> Fixing issue with sync-from-remote without remote (#570)

- HISTORY.rst
- config/settings/base.py
- docs_manual/admin_config.rst
- variants/templates/variants/filter_result/row.html
Closes: #576
Related-Issue: #570
CC @your-highness once you confirm in the ticket that the links work, I will create a backport of this to v1.2.x/anthenea branch.
> Adding feature to enable and configure link-out to HGMD (#576)

- HISTORY.rst
- svs/forms.py
- svs/templates/svs/filter_result/row_sv.html
- svs/templates/svs/filter_result/table.html
- svs/templates/svs/scripts.html
- svs/templates/svs/second_hit.html
- svs/tests/test_views.py
- svs/urls.py
- svs/views.py
- varfish/static/js/variant_carrier.js
- variants/queries.py
- variants/query_presets.py
- variants/templates/variants/filter_result/row.html
- variants/templates/variants/filter_result/secondhit_modal.html
- variants/templates/variants/filter_result/table.html
- variants/templates/variants/scripts.html
- variants/templates/variants/second_hit.html
- variants/tests/test_query_presets.py
- variants/tests/test_views.py
- variants/urls.py
- variants/views.py
Closes: #573
Related-Issue: #573
> Adding second-hit search for small variants & SVs (#573, #574)

- HISTORY.rst
- geneinfo/tests/factories.py
- variants/file_export.py
- variants/models.py
- variants/queries.py
- variants/tests/factories.py
- variants/tests/test_file_export.py
- variants/views.py
> Add_Transcripts_GnomadAD_constraints_and_clinvar_reports_in_the_export

- HISTORY.rst
- variants/forms.py
- variants/templates/variants/filter_form/frequency.html
- variants/views.py
Closes: #597
Related-Issue: #597
> Fixed bug where Exac & 1000g settings were not shown in frequency tab for GRCh37

- HISTORY.rst
- variants/templates/variants/filter_form/frequency.html
Closes: #607
Related-Issue: #607
> Form template reports error if genomebuild variable is not set.

- HISTORY.rst
Closes: #602
Related-Issue: #602
> Preparing v1.2.2 stable release

- HISTORY.rst
- variants/templates/variants/filter_result/table.html
Related-Issue: #641
Closes: #641
> Warning in case of truncated display (#641).

- HISTORY.rst
- docker/Dockerfile
Related-Issue: #660
Closes: #660
> Fixing Docker builds (#660) backport

- HISTORY.rst
- docker/Dockerfile
Related-Issue: #660
Closes: #660
> Fixing Docker builds (#660)

- variants/templatetags/variants_tags.py
> Fixed wrong colored WIP result rows (#673)

- HISTORY.rst
- clinvar_export/clinvar_xml.py
- clinvar_export/views_ajax.py
Closes: #677
Related-Issue: #677
> Fixing ClinVar submission XML generation (#677)

- HISTORY.rst
- clinvar_export/clinvar_xml.py
- clinvar_export/views_ajax.py
Closes: #677
Related-Issue: #677
> Fixing ClinVar submission XML generation (#677) (backport)

- HISTORY.rst
- clinvar_export/management/commands/refresh_individuals.py
- clinvar_export/models.py
- clinvar_export/tasks.py
- clinvar_export/tests/test_models.py
> Regular refresh ClinVar individual from Case (#158) (backport)

- HISTORY.rst
- clinvar_export/management/commands/refresh_individuals.py
- clinvar_export/models.py
- clinvar_export/tasks.py
- clinvar_export/tests/test_models.py
> Regular refresh ClinVar individual from Case (#158)

- HISTORY.rst
- varfish/vueapp/src/components/ClinvarExportApp.vue
- varfish/vueapp/src/components/SubmissionList.vue
- varfish/vueapp/src/store/modules/clinvarExport.js
Related-Issue: #667
Related-Issue: #668
Closes: #667
Closes: #668
> Fixing ClinVar export editor timing issues (#667, #668).

- HISTORY.rst
- variants/templates/variants/var_details/freq_overview.html
> Fixing hemizygous count display in fold-outs (#646)

- HISTORY.rst
- variants/templates/variants/var_details/freq_overview.html
> Fixing hemizygous count display in fold-outs (#646) (backport)

- HISTORY.rst
- clinvar_export/models.py
> Fixing clinvar submission sex/gender update (#686) (backport)

- HISTORY.rst
- clinvar_export/models.py
> Fixing clinvar submission sex/gender update (#686)

- HISTORY.rst
- clinvar_export/clinvar_xml.py
> Fixing issue with phenotype name in Clinvar (#689)

- HISTORY.rst
- clinvar_export/clinvar_xml.py
> Fixing issue with phenotype name in Clinvar (#689) (backport)

- HISTORY.rst
- variants/templates/variants/filter_result/clinvar_indicator.html
- variants/templates/variants/var_details/clinvar.html
- variants/vueapp/src/components/SmallVariantDetailsClinvar.vue
- variants/vueapp/src/components/SmallVariantFilterResultsTableVariantIcons.vue
Closes: #693
Related-Issue: #693
Projected-Results-Impact: None
> Changing ClinVar link-out to VCV entry instead of coordinates (#693)

- HISTORY.rst
- clinvar_export/vueapp/src/api/clinvarExport.js
- clinvar_export/vueapp/src/store/modules/clinvarExport.js
- clinvar_export/vueapp/tests/unit/clinvarExport/api.spec.js
Closes: #713
Related-Issue: #713
> Bugfix that allow clinvar export submission set deletion (#713).

- HISTORY.rst
- Makefile
- variants/vueapp/package.json
- variants/vueapp/src/components/SmallVariantFilterForm.vue
- variants/vueapp/src/components/SmallVariantFilterResultsTable.vue
Closes: #718
Related-Issue: #718
> Fixing issue with icon in vue3 variants app (#718).

- HISTORY.rst
- variants/vueapp/src/components/SmallVariantFilterResultsTable.columnDefs.js
- variants/vueapp/src/components/SmallVariantFilterResultsTableFrequency.stories.js
- variants/vueapp/src/components/SmallVariantFilterResultsTableFrequency.vue
- variants/vueapp/src/main.js
Closes: #708
Related-Issue: #708
> Warn if non-selected frequency is high (#708)

- HISTORY.rst
- variants/schemas/case-query-v1.json
- variants/vueapp/src/stores/filterQuery.js
Closes: #749
Related-Issue: #749
> Fix query schema (#749).

- HISTORY.rst
- requirements/base.txt
Closes: #750
Related-Issue: #750
> Bumping sodar-core dependency (#750).

- HISTORY.rst
- svs/tasks.py
Closes: #757
Related-Issue: #757
> Fix bug in SV background building (#757)

- varfish/vueapp/vite.config.js
No-Related-Issue: small build issue only
> Fixing vite build for production.

- HISTORY.rst
- variants/tests/test_schemas.py
- variants/vueapp/src/stores/filterQuery.js
Closes: #753
Related-Issue: #753
> Fix bug in filtration form with max. exon dist (#753)

- HISTORY.rst
- clinvar_export/vueapp/src/main.js
- variants/views.py
- variants/vueapp/src/components/ColumnControl.vue
- variants/vueapp/src/components/FilterApp.vue
- variants/vueapp/src/components/FilterResultsTable.columnDefs.js
- variants/vueapp/src/components/FilterResultsTable.vue
- variants/vueapp/src/stores/filterQuery.js
> Extra annos in Vue.js filtration (#755).

- HISTORY.rst
- variants/vueapp/src/components/FilterResultsTableVariantIcons.vue
Closes: #745
Related-Issue: #745
> Fix variant icon display (#745).

- CONTRIBUTORS.rst
- docs_manual/index.rst
- docs_manual/smallprint.rst
Closes: #772
Related-Issue: #772
> Adding attributions to manual (#772).

- HISTORY.rst
- cases/tests/test_permissions_ajax.py
- cases/tests/test_views_ajax.py
- cases/urls.py
- cases/views_ajax.py
- cases/vueapp/src/api/cases.js
- cases/vueapp/src/components/CaseDetailHeader.vue
- cases/vueapp/src/stores/cases.js
- cases/vueapp/tests/unit/cases/api.spec.js
- cases/vueapp/tests/unit/cases/store.cases.spec.js
- varfish/vueapp/components.d.ts
Closes: #743
Related-Issue: #743
> Case permissions in Vue.js (#743)

- HISTORY.rst
- variants/vueapp/src/stores/filterQuery.js
Closes: #794
Related-Issue: #794
> Fixing bug in Vue.js filtration without prior query (#794).

- HISTORY.rst
- svs/bg_db.py
Closes: #790
Related-Issue: #790743
> Fixing bug in SV bg db generation (#792).

- variants/vueapp/src/stores/filterQuery.js
Closes: #800
Related-Issue: #800
> Fix Vue.js variant filter query presets (#800)

- cases/vueapp/src/api/cases.js
- cases/vueapp/src/components/CaseDetail.vue
- cases/vueapp/src/components/CaseDetailHeader.vue
- cases/vueapp/src/stores/case-details.js
- docker/Dockerfile
- variants/views/api/__init__.py
- variants/vueapp/src/components/FilterApp.vue
- variants/vueapp/src/components/FilterAppHeader.vue
- variants/vueapp/src/components/FilterFormEffectPane.vue
- variants/vueapp/src/components/VariantDetailsCallDetails.vue
- variants/vueapp/src/components/VariantDetailsGene.vue
- variants/vueapp/src/stores/filterQuery.js
- variants/vueapp/src/stores/variantDetails.js
Closes: #806
Related-Issue: #806
> Making variant detail display more robust (#806)

- HISTORY.rst
- variants/vueapp/src/stores/filterQuery.js
Closes: #820
Related-Issue: #820
> Fixing bug in quick preset loading in vue filter app (#820)

- HISTORY.rst
- svs/templates/svs/filter_result/row_sv.html
- variants/templates/variants/filter_result/row.html
- variants/templatetags/variants_tags.py
Closes: #748
Related-Issue: #748
> Added locus link-out for genoox Franklin.

- HISTORY.rst
- variants/vueapp/src/components/FilterFormQualityPane.vue
- variants/vueapp/tests/unit/components/FilterFormQualityPane.spec.js
Closes: #825
Related-Issue: #825
> Removing template settings in quality form tab (#825)

- HISTORY.rst
- variants/vueapp/src/components/FilterForm.vue
- variants/vueapp/src/components/FilterFormGenesRegionsPane.vue
- variants/vueapp/tests/unit/components/FilterFormGenesRegionsPane.spec.js
Closes: #823
Related-Issue: #823
> Removing gene blocklist from vue filter app (#823)

- geneinfo/serializers.py
- geneinfo/urls.py
- geneinfo/views_api.py
- variants/vueapp/src/components/FilterFormGenesRegionsPane.vue
- variants/vueapp/src/components/TokenizingTextarea.vue
- variants/vueapp/tests/data/localPanelResponse.json
- variants/vueapp/tests/data/panelapp-response-page1.json
- variants/vueapp/tests/data/panelapp-response-page2.json
- variants/vueapp/tests/data/panelapp-response-page3.json
- variants/vueapp/tests/data/panelapp-response-page4.json
- variants/vueapp/tests/unit/components/FilterFormGenesRegionsPane.spec.js
Closes: #824
Related-Issue: #824
> feat: Adding presets to gene allowlist in vue filter app (#824)

- svs/vueapp/src/components/SvDetails.vue
- svs/vueapp/src/components/SvFilterFormQuickPresets.vue
Previously, the setting was not properly set because of issues with the value wrapper.
> fix: genotype criteria quick preset can now be applied

- docs_manual/admin_ingest.rst
Fixing versions in the variant ingest documentation.
> docs: fix admin_ingest.rst

- svs/models/jobs.py
> fix: issue with generating strucvar query JSON and empty values

- .github/workflows/release-please.yml
> ci: use bot token (for varfish-bot) in release-please

- cases/vueapp/src/stores/cases.js
- cases/vueapp/tests/unit/cases/store.cases.spec.js
- varfish/vueapp/components.d.ts
- varfish/vueapp/src/varfish/helpers.js
- variants/query_schemas.py
- variants/vueapp/src/components/FilterResultsTable.vue
- variants/vueapp/src/stores/filterQuery.js
> fix: error in parsing chromosomal coordinates in genomic regions (#989)

- variants/vueapp/src/stores/filterQuery.js
> fix: fielderror cannot resolve keyword genotype into field (#988)

- variants/vueapp/src/stores/filterQuery.funcs.js
> fix: genomic regions are not stored correctly (#992)

- utils/docker/Dockerfile
> fix: add missing dependencies to Dockerfile

- utils/docker/Dockerfile
> build: speedup docker builds by using binary protobuf package (#997)

- utils/docker/build-docker.sh
> build: fix docker build script

- utils/docker/Dockerfile
> build: fix Dockerfile to install postgres-client-12

- variants/vueapp/src/components/FilterFormQuickPresets.vue
- variants/vueapp/src/stores/filterQuery.funcs.js
- variants/vueapp/src/stores/filterQuery.js
> fix: resolve issue with sv quick preset initialization

- varfish/vueapp/src/varfish/components/VariantDetailsFlags.vue
- variants/vueapp/src/components/VariantDetails.vue
> fix: make flagging SVs possible again (#1006)

- variants/vueapp/src/components/FilterFormEffectPane.vue
- variants/vueapp/tests/unit/components/FilterFormEffectPane.spec.js
> fix: value in exon max dist prevents submitting query (#993)

- variants/views/api/__init__.py
> fix: resolve issue in project QC with variant statistics API

- cases/plugins.py
- cases/templates/cases/_details_card.html
- cases/templates/cases/_search_item.html
- cases/templates/cases/_search_results.html
- cases/templates/cases/case/indicator_rel_error.html
- cases/templates/cases/case/indicator_sex_error.html
- cases/templates/cases/case/item.html
- cases/templatetags/cases_tags.py
- varfish/templates/users/login.html
> fix: re-enable searching for cases and list in project overview (#1004)

- cases/templatetags/cases_tags.py
- variants/templatetags/variants_tags.py
> fix: add necessary tag for login page

- cases/views.py
- config/settings/base.py
- config/settings/local.py
- config/settings/production.py
- config/urls.py
- svs/vueapp/src/components/GenomeBrowser.tracks.js
- varfish/vueapp/vite.config.js
> feat: provide genome browser through reverse proxy (#1011)

- svs/views/ajax/queries.py
- variants/rules.py
- variants/tests/factories.py
- variants/tests/test_permissions_ajax.py
- variants/tests/test_permissions_api.py
- variants/views/api/__init__.py
> fix: permissions broken for smallvariant query (#1013)

- cases_import/admin.py
- cases_import/apps.py
- cases_import/models.py
- cases_import/rules.py
- cases_import/serializers.py
- cases_import/tests/factories.py
- cases_import/urls.py
- cases_import/views_api.py
- config/settings/base.py
- config/urls.py
> feat: bootstrapping cases_import app (#1019)

- svs/query_presets.py
- svs/tests/test_query_presets.py
> fix: high quality as default for sv filtration (#984)

- svs/tests/test_views_ajax_user_annos.py
- svs/views/ajax/user_annos.py
- variants/tests/test_views_api.py
- variants/urls/__init__.py
- variants/views/api/__init__.py
> fix: small variant and svs load all available flags and comments (#1032)

- geneinfo/tests/_test_views.py
- variants/tests/test_views.py
- variants/vueapp/src/components/FilterResultsTable.vue
- variants/vueapp/src/stores/variantFlags.js
> fix: further speed improvement loading small variant table (#1037)

- Pipfile.lock
- importer/models.py
> fix: make SV import work when feature-effects are empty

- Pipfile.lock
> fix: updating Pipfile.lock (#1054)

- svs/vueapp/src/components/SvFilterResultsTable.vue
> fix: properly link out in SV results table (#1068)

- variants/vueapp/src/components/FilterApp.vue
> feat: enable SpliceAI and CADD-PHRED columns if available (#1069)

- variants/vueapp/src/components/FilterApp.vue
- variants/vueapp/src/stores/filterQuery.js
> feat: use CADD as default prioritization score (#1063)

- variants/submit_filter.py
> feat: logging number of query result rows (#1066)

- .github/workflows/main.yml
- variants/views/api/__init__.py
- variants/vueapp/src/components/FilterResultsTable.vue
> feat: allow sorting by extra annotations (#1070)

- variants/query_presets.py
- variants/tests/test_query_presets.py
> fix: whole transcript preset should include non coding transcripts (#1044)

- variants/vueapp/src/components/VariantDetailsFreqs.vue
> fix: add missing labels in variant frequency details (#1064)

- variants/query_schemas.py
- variants/schemas/case-query-v1.json
> fix: compound het and recessive mode broken (#1058)

- variants/tests/test_views_api.py
- variants/views/api/__init__.py
> fix: previous query is not restricted to user (#1030)

- variants/models/jobs.py
> fix: exomiser prioritization broken for some genes (#1085)

- svs/vueapp/src/stores/svFlags.js
- varfish/vueapp/src/varfish/helpers.js
> fix: fix SV flagging issue with BND/INS types

- utils/docker/Dockerfile
> chore: bump varfish-server-worker to 0.10.1

- cases/vueapp/src/main.js
- svs/vueapp/src/components/GenomeBrowser.vue
- svs/vueapp/src/components/SvDetails.fields.ts
- svs/vueapp/src/components/SvDetails.vue
- svs/vueapp/src/components/SvDetailsClinvar.vue
- svs/vueapp/src/components/SvDetailsGenes.vue
- svs/vueapp/src/components/SvDetailsModalWrapper.vue
- svs/vueapp/src/components/SvFilterResultsTable.vue
- svs/vueapp/src/stores/detailsSv.ts
- variants/vueapp/src/components/VariantDetailsGene.stories.js
- variants/vueapp/src/components/VariantDetailsGene.vue
- variants/vueapp/tests/unit/components/VariantDetailsTxCsq.spec.js
> feat: bring over small variant details changes to SVs (#1089)

- svs/vueapp/src/components/SvDetailsGenes.vue
- svs/vueapp/src/components/SvFilterResultsTable.vue
- svs/vueapp/src/stores/svFlags.js
- varfish/vueapp/src/varfish/helpers.js
> feat: improving gene list display for many genes (#1092)

- variants/vueapp/src/components/VariantDetailsGene.vue
- variants/vueapp/src/components/VariantDetailsVariantTools.vue
> fix: order link-outs alphabetically

- variants/vueapp/src/components/VariantDetails/Freqs.vue
- variants/vueapp/src/components/VariantDetails/FreqsAutosomal.vue
> fix: making gnomAD frequency display work again

- cases/vueapp/src/main.js
- svs/vueapp/src/components/SvFilterApp.vue
- svs/vueapp/src/components/SvFilterResultsTable.vue
- variants/vueapp/src/components/FilterApp.vue
- variants/vueapp/src/components/FilterResultsTable.vue
> fix: table in default sorting after returning from details (#1109)

- variants/vueapp/src/components/FilterApp.vue
> fix: optional columns selected with each variant detail view (#1111)

- svs/vueapp/src/components/SvDetails/Genes.vue
- varfish/vueapp/components.d.ts
- variants/vueapp/src/components/VariantDetails/Gene.vue
NB: WIP, missing for SV details view
> feat: integrate ClinGen, sHet, rCNV gene information

- maintenance/management/commands/generate_result_set.py
- utils/kickoff_orphaned_annotation_query.py
- variants/queries.py
- variants/query_schemas.py
- variants/schemas/case-query-v1.json
- variants/tests/data/query_settings.py
- variants/tests/test_utils.py
- variants/utils.py
> fix: lift over orphaned variant annotations (#1124)

- variants/vueapp/src/components/FilterResultsTable.vue
> fix: table sorting on variants result page

- variants/vueapp/src/components/VariantDetails/VariantTools.vue
> fix: properly handle all-null/"." REVEL etc. scores (#1117)

- .github/workflows/deps-report.yml
- Pipfile
- Pipfile.lock
> ci: add new deps-report action and fixup pipfile.lock

- cases_import/models/executors.py
- cases_import/tests/data/singleton_strucvars.yaml
- cases_import/tests/snapshots/snap_test_models_executor.py
- cases_import/tests/test_models_executor.py
- config/settings/base.py
> feat: integration of worker "strucvars ingest"

- utils/docker/Dockerfile
> build: speedup Docker built with worker from upstream image

- maintenance/management/commands/generate_result_set.py
- utils/docker/Dockerfile
- varfish/vueapp/src/varfish/api/mehari.ts
> fix: mehari call

- utils/docker/Dockerfile
> fix: structural variant worker call

- varfish/vueapp/src/varfish/api/mehari.ts
> fix: rollback mehari call

- variants/vueapp/src/stores/variantQuery.js
> fix: resultset store issue

- Pipfile.lock
> fix: updated pipfile lock

- cases/vueapp/src/stores/caseDetails.ts
- svs/vueapp/src/components/SvFilterApp.vue
- varfish/vueapp/components.d.ts
- variants/vueapp/src/components/FilterApp.vue
- variants/vueapp/src/components/FilterResultsTable.vue
> fix: table sorting settings not preserved

- cases/vueapp/src/components/CaseDetail/QcTableAlignmentStats.vue
> fix: suppress BAM QC table if BAM stats missing

- cases_import/plugins.py
> fix: switch case import data port setting to type integer

- svs/vueapp/src/components/SvDetails/Genes.vue
- variants/vueapp/src/components/VariantDetails/Clinvar.vue
- variants/vueapp/src/components/VariantDetails/ClinvarFreqPlot.vue
> fix: adapting strucvar details to latest annonars changes (#1229)

- cases_import/models/executors.py
- importer/models.py
> fix: query result sets not created on case import (#1241)

- svs/vueapp/src/components/SvFilterForm/Footer.vue
- svs/vueapp/src/components/SvFilterForm/GenesRegionsPane.vue
- variants/vueapp/src/components/FilterForm/Footer.vue
- variants/vueapp/src/components/FilterForm/GenesRegionsPane.vue
- variants/vueapp/src/components/TokenizingTextarea.vue
- variants/vueapp/src/components/VariantDetails/Gene.vue
- variants/vueapp/tests/unit/components/TokenizingTextarea.spec.js
> fix: adding large panels causes incorrect linting errors (#1184)

- config/settings/base.py
> feat: allow using secret files for secrets (#1257)

- cases/plugins.py
- variants/models/case.py
> feat: searching for cases only works with exact match (#1252)

- svs/models/jobs.py
> fix: strucvar filtration always run with grch37 (#1271)

- Pipfile.lock
- cases/tests/test_permissions_ajax.py
- cases/tests/test_permissions_api.py
- cases/tests/test_views_ajax.py
- cases/urls.py
- cases/views_ajax.py
- cases/views_api.py
- cases/vueapp/src/api/caseClient.ts
- cases/vueapp/src/components/CaseDetail/Header.vue
- cases/vueapp/src/components/CaseDetailApp.vue
- cases/vueapp/src/stores/caseDetails.ts
> fix: deleting a case broken (#1162)

- svs/vueapp/src/components/SvFilterApp.vue
- svs/vueapp/src/stores/svQuery.js
> fix: sv results page shows previous results after sv details (#1302)

- svs/vueapp/src/components/SvFilterResultsTable.vue
- svs/vueapp/src/stores/svResultSet.ts
> fix: allow changing no. of rows and page switch in sv table (#1268)

- svs/vueapp/src/components/GenomeBrowser.vue
> fix: igv shows error for grch38 svs (#1274)

- svs/vueapp/src/components/SvFilterResultsTable.vue
- svs/vueapp/src/stores/svFlags.ts
> fix: color of sv flags does not depend on summary status (#1260)

- variants/models/scores.py
> fix: exomiser parameters are wrong (#947)

- clinvar_export/vueapp/src/components/SubmissionList.vue
- varfish/vueapp/src/varfish/components/VariantDetails/Flags.vue
- variants/file_export.py
- variants/schemas/case-query-v1.json
> feat: change label of final causativereported to final report (#665)

- annots-table.diff
- maintenance/management/commands/generate_result_set.py
- maintenance/management/commands/repair_result_set.py
- svs/vueapp/src/components/StrucvarDetailsNavi/lib.ts
- svs/vueapp/src/views/StrucvarDetails/lib.ts
- variants/utils.py
- variants/vueapp/src/components/FilterResultsTable.vue
> fix: current state of special result set (#1377)

- varfish/vueapp/src/varfish/components/CommentsCard/CommentsCard.vue
- varfish/vueapp/src/varfish/components/FlagsCard/FlagsCard.vue
- variants/views/api/__init__.py
- variants/vueapp/src/components/AcmgRatingCard/AcmgRatingCard.stories.ts
- variants/vueapp/src/components/AcmgRatingCard/AcmgRatingCard.vue
- variants/vueapp/src/components/FilterResultsTable.vue
- variants/vueapp/src/stores/variantAcmgRating/store.ts
- variants/vueapp/src/stores/variantComments.ts
- variants/vueapp/src/stores/variantFlags.ts
- variants/vueapp/src/views/SeqvarDetails/SeqvarDetails.vue
> fix: special result row set not updating when flags are updated (#1378)

- variants/vueapp/src/components/SeqvarDetailsNavi/SeqvarDetailsNavi.vue
> fix: Jump to IGV Linkout in back button

- svs/vueapp/src/api/strucvarClient/client.ts
- svs/vueapp/src/stores/strucvarFlags/store.ts
- svs/vueapp/src/stores/svQuery.js
- svs/vueapp/src/stores/svResultSet.ts
- svs/vueapp/src/views/StrucvarDetails/StrucvarDetails.vue
- variants/vueapp/src/components/FilterResultsTable.vue
- variants/vueapp/src/views/SeqvarDetails/SeqvarDetails.vue
> fix: returning from sv details shows wrong result set (#1438)

- svs/vueapp/src/stores/svQuery.js
- varfish/vueapp/package-lock.json
- varfish/vueapp/package.json
- variants/vueapp/src/components/FilterForm.vue
- variants/vueapp/src/components/FilterForm/ExportPane.vue
- variants/vueapp/src/stores/variantQuery.js
> feat: add settings export and import to the vue interface (#1276)

- svs/vueapp/src/components/SvFilterForm.vue
- varfish/vueapp/src/varfish/components/FilterForm/DevPane.vue
- variants/vueapp/src/components/FilterForm.vue
> feat: add settings export and import to vue sv interface (#1453)

- variants/vueapp/src/stores/variantQuery.js
> fix: query preset cannot add gene regions presets (#1166)

- variants/urls/presets.py
- variants/vueapp/src/stores/queryPresets.ts
> fix: query preset removing a quick preset does not remove preset (#1165)

- variants/vueapp/src/components/FilterApp/Header.vue
- variants/vueapp/src/components/QueryPresets/SetEditor.vue
> fix: query presets cannot add new quick preset (#1164)

- cases/vueapp/src/router/index.ts
- svs/vueapp/src/components/SvFilterResultsTable.vue
- svs/vueapp/src/views/StrucvarDetails/StrucvarDetails.vue
- variants/vueapp/src/components/FilterApp.vue
- variants/vueapp/src/components/FilterResultsTable.vue
- variants/vueapp/src/stores/variantDetails.ts
- variants/vueapp/src/views/SeqvarDetails/SeqvarDetails.vue
> fix: variant icons leads to wrong position on details page (#1315)

- variants/vueapp/src/components/FilterResultsTable.vue
> feat: artifact button needs hover description (#1118)

- varfish/tests/drf_spectacular/varfish_api_schema.yaml
- varfish/vueapp/src/varfish/components/CommentsCard/CommentsCard.vue
- varfish/vueapp/src/varfish/components/FlagsCard/FlagsCard.vue
- variants/serializers/__init__.py
- variants/tests/test_views_api.py
- variants/urls/__init__.py
- variants/views/ajax/__init__.py
- variants/views/api/__init__.py
- variants/vueapp/src/api/variantClient/client.ts
- variants/vueapp/src/stores/variantFlags.ts
> feat: allow to see flags for same variant from other cases (#733)

- variants/file_export.py
- variants/models/scores.py
- variants/tests/test_file_export.py
> fix: file export mehari call is external (#1535)

- config/settings/base.py
- env.example
- variants/serializers/__init__.py
> fix: gene allowlist validation inconsistent in front/backend (#1532)

- svs/serializers/user_annos.py
- svs/urls.py
- svs/views/ajax/user_annos.py
- svs/vueapp/src/api/strucvarClient/client.ts
- svs/vueapp/src/stores/strucvarFlags/store.ts
- svs/vueapp/src/stores/svComments.ts
- varfish/tests/drf_spectacular/varfish_api_schema.yaml
- varfish/vueapp/src/varfish/components/CommentsCard/CommentsCard.vue
> fix: wrong genome build for igv visualization of sv (#1511)

- svs/vueapp/src/components/SvFilterResultsTable.vue
- svs/vueapp/src/stores/svResultSet.ts
- variants/vueapp/src/components/FilterResultsTable.vue
- variants/vueapp/src/stores/variantResultSet.ts
> feat: highlight clicked row when returning from var details (#1526)

- svs/vueapp/src/components/StrucvarDetailsNavi/lib.ts
- svs/vueapp/src/components/SvFilterResultsTable.vue
- variants/vueapp/src/components/FilterResultsTable.vue
- variants/vueapp/src/components/FilterResultsTable/CellRendererIgv.vue
- variants/vueapp/src/components/SeqvarDetailsNavi/lib.ts
> fix: adjust mt chromosome in igv calls (#1562)

- variants/queries.py
- variants/tests/test_queries.py
> fix: effects all does not catch empty annotations (#1578)

- variants/vueapp/src/api/queryPresetsClient.ts
- variants/vueapp/src/components/QueryPresets.vue
> fix: cloning a user defined quick preset does not work (#1482)

- Makefile
- cases/vueapp/src/api/caseClient.ts
- cases/vueapp/src/components/CaseDetail/CardVariantQc.vue
- cases/vueapp/src/components/CaseDetail/QcTableVarStats.vue
- cases/vueapp/src/stores/caseDetails.ts
- cases/vueapp/tests/data/caseDetailsStoreData.json
- cases/vueapp/tests/unit/cases/CaseDetail/QcTableVarStats.spec.js
- varfish/tests/drf_spectacular/varfish_api_schema.yaml
- varfish/vueapp/components.d.ts
- variants/plugins.py
- variants/serializers/__init__.py
- variants/urls/__init__.py
- variants/views/ajax/__init__.py
- variants/views/api/__init__.py
> feat: qc values thresholds should be adjustable (#1530)

- cases/views.py
- config/settings/base.py
> feat: hgmd pro link out missing in the vue interface (#1632)

- cases/vueapp/src/plugins/vuetify.ts
- varfish/vueapp/.eslintignore
- varfish/vueapp/.storybook/plugins/vuetify.ts
- variants/vueapp/src/views/SeqvarDetails/SeqvarDetails.vue
> fix: ugprade rfl to adjust to latest annonars and ClinVar XML changes (#1678)

- frontend/Makefile
> fix: frontend build fails on machines less than 32gb ram (#1720)

- backend/svs/models/jobs.py
> fix: caller splitting for old cases (#1741)

- backend/svs/models/jobs.py
> fix: coerce FORMAT/cn to int when writing SV VCF (#1743)

- backend/varfish/users/management/commands/initdev.py
> feat: add manage.py initdev command (#1767)

- backend/Makefile
- backend/varfish/spectacular_utils.py
- backend/varfish/tests/drf_openapi_schema/varfish_api_schema.yaml
- frontend/ext/varfish-api/src/lib/schemas.gen.ts
- frontend/ext/varfish-api/src/lib/types.gen.ts
> fix: spectacular integration with pydantic field

- frontend/Makefile
- frontend/src/cases/components/CaseDetail/CardTerms.vue
- frontend/src/variants/components/HpoTermInput.vue
> fix: case overview diseases terms input missing omim (#1759)

- backend/varfish/spectacular_utils.py
- backend/varfish/tests/drf_openapi_schema/varfish_api_schema.yaml
- frontend/ext/varfish-api/src/lib/schemas.gen.ts
- frontend/ext/varfish-api/src/lib/types.gen.ts
> fix: make Optional work with spectacular

- backend/variants/models/case.py
> fix: case search still broken (#1803)

- backend/variants/models/case.py
> fix: sort case search results (#1810)

- backend/seqvars/models.py
- backend/varfish/tests/drf_openapi_schema/varfish_api_schema.yaml
- frontend/ext/varfish-api/src/lib/schemas.gen.ts
- frontend/ext/varfish-api/src/lib/types.gen.ts
> feat: genotype choice enabled and non_het (#1815)

- frontend/package-lock.json
- frontend/package.json
- frontend/src/cases/components/CaseDetailApp.vue
- frontend/src/cases/router/index.ts
- frontend/src/seqvars/App.vue
- frontend/src/seqvars/components/FrequencySelect/FrequencySelect.vue
- frontend/src/seqvars/components/GenotypeSelect/GenotypeSelect.vue
- frontend/src/seqvars/components/GenotypeSelect/InheritanceModeControls.vue
- frontend/src/seqvars/components/GenotypeSelect/utils.ts
- frontend/src/seqvars/components/Item.vue
- frontend/src/seqvars/components/PredefinedQueryList.vue
- frontend/src/seqvars/components/QueryList.vue
- frontend/src/seqvars/components/utils.ts
- frontend/src/seqvars/views/SeqvarsFiltration.vue
aims to fix all of #1816
This also puts it into the embedded vue app, still have to figure out why we get missing assets there:
(worked in storybook)
> feat: seqvar item modified & revert 

- frontend/src/svs/components/SvFilterApp.vue
- frontend/src/variants/components/FilterApp.vue
- frontend/src/variants/components/HpoTermInput.vue
> fix: show visible response if user enters an invalid hpo term (#1791)

- backend/variants/models/case.py
- frontend/src/cases/components/ModalTermsEditor.vue
- frontend/src/variants/components/FilterForm/PrioritizationPane.vue
- frontend/src/variants/components/HpoTermInput.vue
> fix: hpo terms not findable (#1814)

- frontend/src/variants/components/FilterApp.vue
> fix: results table loses sorting after variant details (#1211)

- frontend/src/variants/components/QueryPresets/SetEditor.vue
> fix: set order of quick presets in dropdown (#1479)

- backend/maintenance/management/commands/remove_invalid_queries.py
- backend/variants/query_schemas.py
- backend/variants/tests/data/query_settings.py
- backend/variants/tests/test_schemas.py
> feat: command to delete invalid queries with invalid settings (#1807)

- frontend/src/svs/views/StrucvarFilterLegacy/StrucvarFilterLegacy.vue
- frontend/src/variants/views/SeqvarFilterLegacy/SeqvarFilterLegacy.vue
> fix: complexity setting for filters missing in new interface (#1853)

- frontend/src/svs/views/StrucvarDetails/StrucvarDetails.vue
- frontend/src/variants/views/SeqvarDetails/SeqvarDetails.vue
> fix: clicking variant modal sidebar does not work (#1849)

- frontend/src/variants/views/SeqvarDetails/SeqvarDetails.vue
> fix: variant modal shifts around during loading (#1850)

- backend/variants/models/presets.py
> fix: cloning query presets results in blank preset (#1837)

- backend/seqvars/models.py
- backend/seqvars/tests/test_models.py
- backend/varfish/tests/drf_openapi_schema/varfish_api_schema.yaml
- frontend/end-to-end-tests/seqvar-filtration.spec.ts
- frontend/ext/varfish-api/src/lib/schemas.gen.ts
- frontend/ext/varfish-api/src/lib/types.gen.ts
- frontend/src/seqvars/components/genotype/InheritanceModeControls.vue
- frontend/src/seqvars/components/genotype/RecessiveControls.vue
- frontend/src/seqvars/components/genotype/constants.ts
@Gregoor could you review the frontend part that you wrote?
> feat: splitting recessive_parent into recessive_{father,mother} (#1867)

- backend/varfish/tests/drf_openapi_schema/varfish_api_schema.yaml
- frontend/ext/varfish-api/src/lib/schemas.gen.ts
- frontend/ext/varfish-api/src/lib/types.gen.ts
- frontend/src/seqvars/components/genotype/InheritanceModeControls.vue
- frontend/src/seqvars/components/genotype/RecessiveControls.vue
> chore: update OpenAPI schema and generated frontend API code

- frontend/src/seqvars/components/SeqvarDetails/SeqvarDetails.vue
- frontend/src/seqvars/views/SeqvarsQuery/SeqvarsQuery.vue
- frontend/src/variants/components/FilterApp.vue
- frontend/src/variants/components/FilterResultsTable.vue
- frontend/src/variants/components/SeqvarDetailsNavi/SeqvarDetailsNavi.vue
- frontend/src/variants/views/SeqvarDetails/SeqvarDetails.vue
- frontend/src/variants/views/SeqvarFilterLegacy/SeqvarFilterLegacy.vue
> feat: enable opening variant details in separate browser tab (#1886)

- utils/docker/Dockerfile
> fix: fix server worker version

- utils/docker/Dockerfile
> chore: upgrade worker in Dockerfile to v0.13.0 (#1922)

- backend/seqvars/models/base.py
- backend/seqvars/models/executors.py
- backend/seqvars/models/protobufs.py
- backend/varfish/tests/drf_openapi_schema/varfish_api_schema.yaml
- frontend/ext/varfish-api/src/lib/@tanstack/vue-query.gen.ts
- frontend/ext/varfish-api/src/lib/schemas.gen.ts
- frontend/ext/varfish-api/src/lib/types.gen.ts
- frontend/ext/viguno-api/src/lib/@tanstack/vue-query.gen.ts
> feat: implement seqvars query results storage (#1951)

- frontend/src/svs/stores/svComments.ts
> fix: strucvar detail lists all comments from project (#1960)

- frontend/src/variants/views/SeqvarDetails/SeqvarDetails.vue
> fix: clicking variant twice fails loading the variant details (#1940)

- .github/workflows/docker-build.yml
> ci: create docker label by SHA tag

- utils/docker/Dockerfile
> chore: bump varfish-server-worker to 0.13.2

- frontend/src/seqvars/components/QueryEditor/EffectsControls.vue
- frontend/src/seqvars/components/QueryEditor/GenotypeControls.vue
- frontend/src/seqvars/components/QueryEditor/PathogenicityPrioControls.vue
- frontend/src/seqvars/components/QueryEditor/PhenotypePrioControls.vue
- frontend/src/seqvars/components/QueryEditor/PredefinedQueryList.vue
- frontend/src/seqvars/components/QueryEditor/QueryEditor.vue
- frontend/src/seqvars/components/QueryEditor/QueryList.vue
- frontend/src/seqvars/components/QueryEditor/groups.ts
- frontend/src/seqvars/components/QueryEditor/ui/CollapsibleGroup.vue
> feat: store collapsible state in local storage (#2043)
